title: Fluxos PS Iamspe
description: Uma lista de fluxos de assistência para o PS do Iamspe
url: https://psiamspe.github.io
baseurl: /fluxos/

theme: just-the-docs
# Theme configurations
search_enabled: true
favicon_ico: /assets/logo.ico
defaults:
  - values:
      layout: default
callouts:
  danger:
    title: Alerta
    color: red
  warning:
    title: Aviso
    color: yellow
  success:
    title: Nota
    color: green
  link:
    title: Observação
    color: blue

# Jekyll plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-spaceship
# jekyll-feed configurations
feed:
  icon: /assets/logo.png
  logo: /assets/logo_2x1.png
# jekyll-spaceship configurations
jekyll-spaceship:
  processors:
    - table-processor
    - mathjax-processor
    - mermaid-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
  mathjax-processor:
    src:
      - https://polyfill.io/v3/polyfill.min.js?features=es6
      - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    config:
      tex:
        inlineMath:
          - ['$','$']
          - ['\(','\)']
        displayMath:
          - ['$$','$$']
          - ['\[','\]']
      svg:
        fontCache: 'global'
    optimize:
      enabled: true
  mermaid-processor:
    syntax:
      code: 'mermaid'
  media-processor:
    default:
      id: 'media-{id}'
      class: 'media'
      width: '100%'
      height: 350
      frameborder: 0
      style: 'outline: none;'
      allow: 'encrypted-media; picture-in-picture'

# Exclusions
exclude:
  - .github/
  - .jekyll-cache/
  - .ruby-lsp/
  - .sass-cache/
  - gemfiles/
  - node_modules/
  - vendor/
  - .gitattributes
  - .gitignore
  - .ruby-version
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - THEME_LICENSE.txt
